- name: Install the mysql packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: "{{mysql_pkgs}}"

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest={{ mysql_server.conf_dir }}/my.cnf
  notify:
   - restart mysql

- name: Start the mysql services
  service: name={{ mysql_server.service_name }} state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_server.root_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items: "{{mysql_hosts}}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create the database's
  mysql_db: name={{ item }} state=present
  with_items: "{{mysql_databases}}"

- name: Create the database users
  mysql_user: name={{ item[0] }}  password={{ item[0] }}
              priv={{ item[0] }}.*:ALL state=present host={{ item[1] }}
  with_nested:
      - "{{mysql_databases}}"
      - "{{mysql_hosts}}"
